project:
  type: book
  output-dir: docs

book:
  title: "Predictive Soil Spectroscopy"
  page-footer:
    left: |
      This training material was written by Jose L. Safanelli, Robert Minarik,
      Tomislav Hengl, and Jonathan Sanderman.
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  site-url: https://soilspectroscopy.github.io/soilspec-workshop/
  repo-url: https://github.com/soilspectroscopy/soilspec-workshop/
  repo-branch: main
  repo-actions: [edit, issue]
  author:
    - name: José Lucas Safanelli
      orcid: 0000-0001-5410-5762
      email: jsafanelli@woodwellclimate.org
      affiliations: Woodwell Climate Research Center
    - name: Robert Minarik
      orcid: 0000-0002-5654-1522
      email: robert.minarik@opengeohub.org
      affiliations: OpenGeoHub Foundation
    - name: Jonathan Sanderman
      orcid: 0000-0002-3215-1706
      email: jsanderman@woodwellclimate.org
      affiliations: Woodwell Climate Research Center
    - name: Tomislav Hengl
      orcid: 0000-0002-9921-5129
      email: tom.hengl@opengeohub.org
      affiliations: OpenGeoHub Foundation
  date: "10/2/2023"
  chapters:
    - index.qmd
    - intro.qmd
    - processing.qmd
    - modeling.qmd
    - chemometrics.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: source
